--- Mapping icons to various constructs within vim. Depends on
--- a nerd font being installed.
---
--- Author: @lararosekelley
--- Last Modified: August 29th, 2025

return {
  icons = {
    dashboard = {
      find_file = " ",
      new_file = " ",
      find_text = "󰈞 ",
      recent_files = " ",
      recent_projects = "󰒋 ",
      config = " ",
      restore_session = " ",
      plugins = " ",
      quit = "󰩈 ",
    },
    whichkey = {
      ai = "󱙺 ",
      delete = " ",
      diagnostics = "󱖫 ",
      find = "󰥨 ",
      fold = " ",
      go = "󰈇 ",
      lsp = "󰅩 ",
      next = " ",
      prev = " ",
      scratch = " ",
      search = " ",
      session = "󰍩 ",
      splits = " ",
      surround = "󰗅 ",
      terminal = " ",
      ui = "󰙵 ",
      wiki = " ",
    },
    misc = {
      dots = "󱗼 ",
      folder = " ",
      time = " ",
    },
    ft = {
      octo = " ",
    },
    mason = {
      package_installed = " ",
      package_pending = " ",
      package_uninstalled = " ",
    },
    dap = {
      Stopped = { " ", "DiagnosticWarn", "DapStoppedLine" },
      Breakpoint = " ",
      BreakpointCondition = " ",
      BreakpointRejected = { " ", "DiagnosticError" },
      LogPoint = "󰦪 ",
    },
    diagnostics = {
      Error = " ",
      Warn = " ",
      Hint = " ",
      Info = " ",
    },
    git = {
      added = " ",
      modified = " ",
      removed = " ",
    },
    kinds = {
      Array = " ",
      Boolean = "󰨙 ",
      Class = " ",
      Codeium = "󰘦 ",
      Color = " ",
      Control = " ",
      Collapsed = "󰘕 ",
      Constant = "󰏿 ",
      Constructor = "󱢛 ",
      Copilot = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Folder = " ",
      Function = "󰊕 ",
      Interface = " ",
      Key = " ",
      Keyword = " ",
      Method = "󰊕 ",
      Module = "󰕳 ",
      Namespace = "󰦮 ",
      Null = "󰟢 ",
      Number = "󰎠 ",
      Object = " ",
      Operator = " ",
      Package = " ",
      Property = " ",
      Reference = " ",
      Snippet = "󱄽 ",
      String = " ",
      Struct = " ",
      Supermaven = " ",
      TabNine = "󰏚 ",
      Text = " ",
      TypeParameter = " ",
      Unit = " ",
      Value = " ",
      Variable = "󰀫 ",
    },
  },
}
